---
name: xl95x5
description: XL9535/XL9555 16-bit I/O expander
version: 1.0.0
groups:
  - gpio
code_owners:
  - jmpmscorp
depends:
  - freertos
thread_safe: yes
targets:
  - esp32
  - esp32c2
  - esp32c3
  - esp32c5
  - esp32c6
  - esp32c61
  - esp32h2
  - esp32p4
  - esp32s2
  - esp32s3
  - esp8266
license: ISC
copyrights:
  - name: jmpmscorp
    year: 2025
